[project]
name = "willcataco-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.124.4",
    "pydantic-settings>=2.11.0",
    "uvicorn>=0.38.0",
]
